home:
    resource: "@HomeBundle/Controller/"
    type:     annotation
    prefix:   /

projekt:
    resource: "@ProjektBundle/Resources/config/routing.yml"
    prefix:   /projekt

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
