services:
    app.projekt_controller:
        class: ProjektBundle\Controller\ProjektController
        arguments: ["@doctrine.orm.entity_manager"]
    app.main_controller:
        class: ProjektBundle\Controller\MainController
        arguments: ["@doctrine.orm.entity_manager"]
    app.submain_controller:
        class: ProjektBundle\Controller\SubmainController
        arguments: ["@doctrine.orm.entity_manager"]
    # app.twig_extension:
    #     class: ProjektBundle\Twig\ProjektExtension
    #     public: false
    #     arguments:
    #             doctrine: "@doctrine" 
    #     tags:
    #         - { name: twig.extension }
