services:
    app.projekt_controller:
        class: ProjektBundle\Controller\ProjektController
        arguments: ["@doctrine.orm.entity_manager"]
    app.main_controller:
        class: ProjektBundle\Controller\MainController
        arguments: ["@doctrine.orm.entity_manager"]
    app.submain_controller:
        class: ProjektBundle\Controller\SubmainController
        arguments: ["@doctrine.orm.entity_manager"]
