<?php

namespace ProjektBundle\Repository;

/**
 * SubmainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubmainRepository extends \Doctrine\ORM\EntityRepository
{
}
