ProjektBundle\Entity\Projekt:
    type: entity
    table: null
    repositoryClass: ProjektBundle\Repository\ProjektRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255
            nullable: TRUE
        image:
            type: string
            length: 255
            nullable: TRUE
        progress:
            type: integer
            nullable: TRUE
    manyToOne:
        user:
          targetEntity: User
          inversedBy: projekts
          joinColumn:
            name: user_id
            referencedColumnName: id
    oneToMany:
        mains:
            targetEntity: Main
            mappedBy: projekt
    lifecycleCallbacks: {  }
